kubernetes-sigs/structured-merge-diff

- merge/leaf_test.go
- merge/set_test.go
- merge/update_test.go
Since we have a type that holds the parser and the typename, we can
simplify the state by holding that ParseableType instead. That actually
simplifies things a little bit.
> Create State with ParseableType

- merge/leaf_test.go
- merge/set_test.go
- merge/update_test.go
Create code so that it's easy to create tests as lists instead of re-specifying a lot of logic in each test, and convert all existing tests.
> Tests as lists

- fieldpath/fromvalue.go
Fix a bug where we re-use the address of the same object in a loop.
> Fix capture bug

- fieldpath/set.go
- fieldpath/set_test.go
Create iterator over the keys of SetNodeMap, mirroring https://github.com/kubernetes-sigs/structured-merge-diff/blob/master/fieldpath/element.go#L179-L184 for the elements of PathElementSet
> Export iterator for SetNodeMap

- value/unstructured.go
- value/unstructured_test.go
This is messing up comparison function like DeepEqual because while the
types are absolutely similar, they're not exactly the same, and it's
very hard to debug.
> ToUnstructured shouldn't return internal types

- merge/update.go
When converting to the same version we already have, don't attempt to go through the hub version
> skip converting to same version

- internal/fixture/state.go
- merge/leaf_test.go
- merge/update.go
The three codepaths added are tested by:
- ```TestUpdateLeaf/update_remove_empty_set``` tests that when all fields are removed from existing owner (either by an Update or forced Apply), their entry is removed from managers
- ```TestUpdateSet/apply_update_apply_reorder``` is an existing test, that now also tests that when updating an object, if the caller would own nothing after the own update, their entry is removed from managers
- ```TestUpdateLeaf/apply_remove_empty_set``` tests that when applying to an object, if the caller provides an empty PSO, their entry is removed from managers
/assign @apelisse 
/assign @kwiesmueller
> Remove empty sets from managers

- internal/fixture/state.go
- merge/obsolete_versions_test.go
- merge/update.go
This is going to be quite important for CRDs (since versions are much more volatile than for in-tree types). And also is going to be useful anyway because all versions eventually get deprecated.
/assign @kwiesmueller @lavalamp @jennybuckley
> Drop managed fields for obsolete versions

- merge/leaf_test.go
- merge/set_test.go
We don't have any cross-version test yet, and they can be easy to make if we assume that the objects are similar in all versions. This will at least test that we carry the proper version where we need to, and that we still can take ownership of fields across versions, etc.
/assign @jennybuckley @kwiesmueller
> Add a few cross-version tests

- internal/fixture/state.go
- internal/fixture/state_test.go
Especially when the struct is in a list because:
```yaml
- a: 1
b: 2
```
panics because of mixed spaces and tabs. A working alternative is to
indent with tabs, but I don't think it's very pleasant:
```yaml
- a: 1
b: 2
```
Update the code so that prefixed tabs from the first line are removed
from all consecutive lines, and keep it that simple.
/assign @lavalamp @jennybuckley @kwiesmueller
> FixTabsOrDie doesn't work well with YAML structs

- fieldpath/set.go
- merge/key_test.go
- merge/nested_test.go
- merge/update.go
- typed/deduced.go
- typed/remove.go
- typed/typed.go
Since ToFieldSet creates a set which only includes leaf nodes, diffing the last applied fieldset and the fieldset generated from the merged object isn't enough to determine which list items to remove, if those items are not scalars (which is why the test we have didn't catch it).
> Fix bug with removing non leaf items

- fieldpath/managers.go
- fieldpath/set.go
- fieldpath/set_test.go
- internal/fixture/state.go
- merge/key_test.go
- merge/multiple_appliers_test.go
- merge/nested_test.go
- merge/update.go
- typed/deduced.go
- typed/remove.go
- typed/toset_test.go
- typed/typed.go
- typed/validate.go
The goal of this PR is to define and implement the behavior of apply when it comes to removing list and map items. The strategy implemented here is most simply defined as:
```
Remove an item on apply, iff someone applied with it last time, without it this time,
and no other applier claims to manage it.
```
This solution works without converting any PSOs or fieldsets, and with linear number of conversions wrt the number of versions (so the number of conversions is only getting increased by a constant factor). The downside is that it requires exposing the concept of whether or not a manager is an updater or an applier.
I have tried to include tests for every possible corner case, like multiple appliers and updaters all of different versions, and fields which are dangling without any owner, …
>  Implement list item and map key removal for multiple appliers

- schema/elements.go
- schema/schemaschema.go
- typed/typed.go
- typed/union.go
- typed/union_test.go
- value/value.go
This does mostly two things:
- Defines the schema for OneOf: multiple oneof can be at the same level (in the same structure),
- Normalizes an object based on oneofs definition: uses the discriminator if present and has changed, uses the difference of fields if they changed, updates the discriminator if present.
And adds tests. This is still not plugged anyway though, so it's not going to do anything.
> Update schema to support oneOf, and normalize objects

- internal/fixture/state.go
- merge/union_test.go
- merge/update.go
- typed/typed.go
- typed/union.go
- typed/union_test.go
Fix a few bugs, change the interface a little, and call unions. Once this gets integrated, kubernetes should be able to support union, as long as the schema properly defines it (which misses a couple of steps).
> Integrate union in Apply/Update path

- internal/testdata/bad-schema.yaml
- internal/testdata/k8s-schema.yaml
- internal/testdata/list.yaml
- internal/testdata/schema.yaml
- internal/testdata/struct.yaml
- merge/key_test.go
- merge/leaf_test.go
- merge/nested_test.go
- merge/obsolete_versions_test.go
- merge/preserve_unknown_test.go
- merge/set_test.go
- merge/union_test.go
- schema/elements.go
- schema/schemaschema.go
- typed/helpers.go
- typed/merge.go
- typed/merge_test.go
- typed/remove.go
- typed/symdiff_test.go
- typed/toset_test.go
- typed/union.go
- typed/union_test.go
- typed/validate.go
- typed/validate_test.go
Ehen deserializing a core type we throw away unknown fields because they don't fit into the go struct, but with CRs we don't throw them away because we are always deserializing into Unstructured. Right now we have no concept in structured-merge-diff of additional properties on a struct, and any fields of an object being set, other than the ones in the schema, make it fail validation.
This could be solved by pruning CRDs, which is being worked on, but still will never always be done because it's backwards incompatible (current CRD validation fields might not always be fully specified).
A more complete solution is to merge struct and map in our schema, and allow additional properties in structs (if a defaultElementType field is set). This addresses issues with CRD unknown fields not always …
> Merge map and struct, allowing for unknown struct fields

- merge/union_test.go
- merge/update.go
- schema/elements.go
- schema/schemaschema.go
- typed/typed.go
- typed/union.go
- typed/union_test.go
We're still using the difference, but only to see if something wrong was sent.
The new logic is to only trust the disicriminator, which means that the
behavior for non-discriminated union is now back to before. It also
means that we can't use that process anymore to normalize applied
unions. Applied unions are normalized by trusting the applied fields
exclusively: applying two fields doesn't work, applying a discriminator
and a different value doesn't work.
Also rename `discriminatedBy` into `discriminatorValue`
> Change union to not "guess" based on difference

- fieldpath/managers.go
- fieldpath/managers_test.go
- internal/fixture/state.go
- merge/conflict.go
- merge/conflict_test.go
- merge/deduced_test.go
- merge/key_test.go
- merge/leaf_test.go
- merge/multiple_appliers_test.go
- merge/nested_test.go
- merge/obsolete_versions_test.go
- merge/preserve_unknown_test.go
- merge/set_test.go
- merge/union_test.go
- merge/update.go
And create a new `versionedSet` object that implements that interface. A
side effect of this change is that the versionedSet is now mostly
immutable (since there are no setters on the interface), if you want to
change a `VersionedSet`, you should probably create a new one.
This will allow us to implement two things:
1. Cached `VersionedSet`: if such an object is not replaced with a new
instance, then we don't have to reserialize it.
2. Lazy `VersionSet`: we don't have to deserialize objects until we
actually need to look at the set.
This is breaking the API.
> Make VersionedSet into an interface

- fieldpath/element.go
- fieldpath/element_test.go
- fieldpath/fromvalue.go
- fieldpath/path.go
- fieldpath/path_test.go
- fieldpath/set.go
- fieldpath/set_test.go
- internal/fixture/state.go
- merge/conflict.go
- merge/deduced_test.go
- merge/leaf_test.go
- merge/multiple_appliers_test.go
- typed/helpers.go
- value/less_test.go
- value/value.go
Prior to these changes:
```
BenchmarkDeducedSimple-12                                   3000            472665 ns/op          139180 B/op       1810 allocs/op
BenchmarkDeducedNested-12                                   1000           1370363 ns/op          401776 B/op       5146 allocs/op
BenchmarkDeducedNestedAcrossVersion-12                      1000           1435743 ns/op          434426 B/op       5527 allocs/op
BenchmarkLeafConflictAcrossVersion-12                       3000            492026 ns/op          147113 B/op       1848 allocs/op
BenchmarkMultipleApplierRecursiveRealConversion-12          1000           2585529 ns/op          805147 B/op       8457 allocs/op
```
After these changes:
```
BenchmarkDeducedSimple-12                                   5000            432763 …
```
> Optimize benchmarks; permit serialization

- fieldpath/element.go
- fieldpath/set.go
```
benchmark                                  old ns/op     new ns/op     delta
BenchmarkFieldSet/insert-20-12             19315         19975         +3.42%
BenchmarkFieldSet/has-20-12                704           699           -0.71%
BenchmarkFieldSet/union-20-12              11495         11874         +3.30%
BenchmarkFieldSet/intersection-20-12       5153          5120          -0.64%
BenchmarkFieldSet/difference-20-12         8763          8780          +0.19%
BenchmarkFieldSet/insert-50-12             62701         65663         +4.72%
BenchmarkFieldSet/has-50-12                873           876           +0.34%
BenchmarkFieldSet/union-50-12              29569         28755         -2.75%
BenchmarkFieldSet/intersection-50-12       10213         9916          -2.91% …
```
> use the technically-correct copy()

- typed/helpers.go
- typed/merge.go
- typed/validate.go
- value/value.go
```
benchmark                       old ns/op     new ns/op     delta
BenchmarkApplyNewObject-12      1937221       1549953       -19.99%
BenchmarkUpdateNewObject-12     2175330       2054741       -5.54%
BenchmarkRepeatedUpdate-12      761351        635385        -16.55%
BenchmarkSetToFields-12         5200          5173          -0.52%
BenchmarkFieldsToSet-12         10336         10240         -0.93%
BenchmarkYAMLToTyped-12         64579         61926         -4.11%
benchmark                       old allocs     new allocs     delta
BenchmarkApplyNewObject-12      6820           6355           -6.82%
BenchmarkUpdateNewObject-12     7901           7398           -6.37%
BenchmarkRepeatedUpdate-12      2264           2035           -10.11%
BenchmarkSetToFields-12         14             14 …
```
> improved memory management

- schema/elements_test.go
- schema/equals.go
- schema/equals_test.go
- typed/merge.go
- typed/typed.go
- value/value.go
This change is a huge improvement:
```
benchmark                                              old ns/op     new ns/op     delta
BenchmarkDeducedSimple-12                              343266        296104        -13.74%
BenchmarkDeducedNested-12                              900868        765058        -15.08%
BenchmarkDeducedNestedAcrossVersion-12                 1004928       799466        -20.45%
BenchmarkLeafConflictAcrossVersion-12                  349167        279827        -19.86%
BenchmarkMultipleApplierRecursiveRealConversion-12     2231486       2149787       -3.66%
benchmark                                              old allocs     new allocs     delta
BenchmarkDeducedSimple-12                              1264           1098           -13.13%
BenchmarkDeducedNested-12 …
```
> reflect.DeepEqual, not even once

- internal/fixture/state.go
- merge/union_test.go
- merge/update.go
- typed/typed.go
```
benchmark                       old ns/op     new ns/op     delta
BenchmarkApplyNewObject-12      1355981       1363050       +0.52%
BenchmarkUpdateNewObject-12     1565341       1228947       -21.49%
BenchmarkRepeatedUpdate-12      443528        396604        -10.58%
BenchmarkSetToFields-12         5154          5107          -0.91%
BenchmarkFieldsToSet-12         10050         10170         +1.19%
BenchmarkYAMLToTyped-12         56860         54439         -4.26%
benchmark                       old allocs     new allocs     delta
BenchmarkApplyNewObject-12      4264           4214           -1.17%
BenchmarkUpdateNewObject-12     4850           3661           -24.52%
BenchmarkRepeatedUpdate-12      1255           1179           -6.06%
BenchmarkSetToFields-12         14             14 …
```
> disable unions, since they're still experimental

- typed/typed.go
- typed/validate.go
```
benchmark                       old ns/op     new ns/op     delta
BenchmarkApplyNewObject-12      1363050       1347076       -1.17%
BenchmarkUpdateNewObject-12     1228947       1160335       -5.58%
BenchmarkRepeatedUpdate-12      396604        384544        -3.04%
BenchmarkSetToFields-12         5107          5214          +2.10%
BenchmarkFieldsToSet-12         10170         10118         -0.51%
BenchmarkYAMLToTyped-12         54439         51352         -5.67%
benchmark                       old allocs     new allocs     delta
BenchmarkApplyNewObject-12      4214           4089           -2.97%
BenchmarkUpdateNewObject-12     3661           3568           -2.54%
BenchmarkRepeatedUpdate-12      1179           1111           -5.77%
BenchmarkSetToFields-12         14             14 …
```
> memory pools for walkers

- internal/testdata/scalar-compare-output.txt
- typed/deduced_test.go
- typed/symdiff_test.go
- typed/typed.go
Speed is not super reliable on laptop because of throttling, allocs should be relevant:
```
benchmark                                             old ns/op     new ns/op     delta
BenchmarkDeducedSimple-8                              103885        86064         -17.15%
BenchmarkDeducedNested-8                              256101        247159        -3.49%
BenchmarkDeducedNestedAcrossVersion-8                 259720        286096        +10.16%
BenchmarkLeafConflictAcrossVersion-8                  85375         89451         +4.77%
BenchmarkMultipleApplierRecursiveRealConversion-8     733484        720364        -1.79%
benchmark                                             old allocs     new allocs     delta
BenchmarkDeducedSimple-8                              877            840 …
```
> Remove merge from Compare

- internal/fixture/state.go
- merge/deduced_test.go
- merge/leaf_test.go
- merge/multiple_appliers_test.go
- merge/pod_test.go
- typed/parser_test.go
- Remove deserialization from benchmarks,
- Add actual pod to test performance,
- Add benchmark for converting objects to TypedValue
> Various benchmarks improvements

- go.mod
- go.sum
- schema/elements.go
- schema/elements_test.go
- schema/equals_test.go
- typed/helpers.go
- typed/merge.go
- typed/remove.go
- typed/validate.go
- vendor/github.com/google/gofuzz/.travis.yml
- vendor/github.com/google/gofuzz/CONTRIBUTING.md
- vendor/github.com/google/gofuzz/LICENSE
- vendor/github.com/google/gofuzz/README.md
- vendor/github.com/google/gofuzz/doc.go
- vendor/github.com/google/gofuzz/fuzz.go
- vendor/github.com/google/gofuzz/go.mod
- vendor/modules.txt
When the schema is big, a lot of time is spent going through the list of each possible type to find the one it's looking for. No memory improvement, pure CPU/time:
```
benchmark                                   old ns/op     new ns/op     delta
BenchmarkOperations/Node/Update-12          576277        434979        -24.52%
BenchmarkOperations/Endpoints/Apply-12      2065245       1664846       -19.39%
BenchmarkOperations/Pod/Update-12           384166        312411        -18.68%
BenchmarkOperations/Node/Apply-12           764054        622976        -18.46%
BenchmarkOperations/Endpoints/Update-12     55470         46779         -15.67%
BenchmarkOperations/Pod/Apply-12            543377        478227        -11.99%
```
> Cache type information in Schema

- internal/fixture/state.go
This is quite trivial, but since we're doing this on every single benchmark step, it's a little misleading to have yaml parsing there ...
> Remove YAML parsing in benchmark

- fieldpath/element.go
- fieldpath/pathelementmap.go
- fieldpath/pathelementmap_test.go
- typed/merge.go
- typed/validate.go
Currently, we index PathElement by turning them into strings, which is neither fast nor accurate.
We can simply use the `PathElementSet` when we need a set, and we can build a map of PathElement to Value when needed using very similar code.
Improvement:
```
benchmark                                              old ns/op     new ns/op     delta
BenchmarkOperations/Pod/Update-12                      187994        162602        -13.51%
BenchmarkOperations/Pod/Apply-12                       525375        452963        -13.78%
BenchmarkOperations/Node/Update-12                     273261        220959        -19.14%
BenchmarkOperations/Node/Apply-12                      760287        667991        -12.14%
BenchmarkOperations/Endpoints/Update-12                32649         32794 …
```
> Use PathElementSet and similar to index PathElement

- merge/real_test.go
We currently were mostly benchmarking creation, apply but not updates,
nor any updates across versions. These new tests show that updates are
extremely expensive for objects that have big "atomic" values because
the comparison is pretty slow.
```
pkg: sigs.k8s.io/structured-merge-diff/merge
BenchmarkDeducedSimple-12                             	   10000	    102086 ns/op	   33768 B/op	     570 allocs/op
BenchmarkDeducedNested-12                             	    3000	    375675 ns/op	  103168 B/op	    1910 allocs/op
BenchmarkDeducedNestedAcrossVersion-12                	    3000	    407410 ns/op	  106689 B/op	    1978 allocs/op
BenchmarkLeafConflictAcrossVersion-12                 	   20000	     91036 ns/op	   31151 B/op	     505 allocs/op
BenchmarkMultipleApplierRecursiveRealConversion-12 …
```
> Add additional benchmarks for "updates"

- value/less_test.go
- value/value.go
Equality doesn't require the same amount of sophistication than ordering
comparison. Implement an Equal function that does just that but does it
much faster.
Benchmark results show up to 96% improvement:
```
benchmark                                                         old ns/op     new ns/op     delta
BenchmarkDeducedSimple-12                                         110083        103256        -6.20%
BenchmarkDeducedNested-12                                         374366        374160        -0.06%
BenchmarkDeducedNestedAcrossVersion-12                            392864        405525        +3.22%
BenchmarkLeafConflictAcrossVersion-12                             89112         89070         -0.05%
BenchmarkMultipleApplierRecursiveRealConversion-12                1564330       1574620 …
```
> Implement equality for Values

- README.md
I'm sure we can also fix the slack link, not sure how to refer to a specific channel.
> Fix wg-apply mailing list link

- value/less_test.go
- value/value.go
Manual cherrypick of #126 to release-1.0 (what is used in 1.16)
This fixes an issue with schemas containing large atomic maps, which, in kubernetes, sometimes caused large CRD objects to take a very long time to update/apply to.
> Cherrypick #126 to 1.0 - Implement equality for Values

- typed/helpers.go
- typed/symdiff_test.go
- typed/validate.go
- typed/validate_test.go
For a while now, any schema errors would result in a very useless error message "invalid atom", this was confusing, and also made debugging wiring the schema and value interface very tricky. This problem was originally caused when I made a schema able to represent something which could possibly be one of multiple types (was needed for CRD support) because we started hitting the "schema error: invalid atom" error before the validation code can generate a more useful error message.
Some examples of this problem (from typed/validate_test.go): 
| input | old error | new error |
|---|---|---|
| **TestSchemaValidation/simple_pair:** |
| `{"key":{"foo":true}}` | `.key: schema error: invalid atom: inlined` | `.key: expected string, got {foo=true}` |
| `{"key":[1, 2]}` | `.key: schema error: …
> Fix useless error message 'invalid atom'

- fieldpath/element.go
- fieldpath/path.go
- value/fields.go
This brings a 5 to 10% time-wise on some of the operations. Might be tremendous improvements on some specific resources though.
> Change equal for path element

- fieldpath/fromvalue.go
- typed/helpers.go
- typed/remove.go
- typed/union.go
- value/value.go
- value/valueunstructured.go
Renames all conversion methods for value.Value
e.g. `Map()` -> `AsMap()`
This removes the implementation of `String() string`.
Without this change, calling String() on a value would behave differently than usually expected in go.
> rename value conversion methods

- typed/helpers.go
- typed/symdiff_test.go
- typed/validate.go
- typed/validate_test.go
Backporting https://github.com/kubernetes-sigs/structured-merge-diff/pull/131 to 1.17
/assign @apelisse @jennybuckley
> Back-port Fix from Jenny for ugly errors to 2.0

- internal/fixture/state.go
Currently, we run each test twice when unions aren't required: once with
and once without them enabled. Since we run with the union enabled
first, legitimate test failures are prepended with "fails when unions
are on" which is misleading since they may not be caused by unions.
Running union tests last removes that mis-leading prefix and makes it
clear if the problem comes from union or not.
> Run non-required union tests last

- value/less_test.go
- value/value.go
Currently, value.Equals doesn't check that the types are different in
both direction: it checks that if lhs is of type A, then rhs must also
be of type A), but it doesn't check that if lhs is not of type A but rhs
is, then they must be different.
Make it more obvious in the test that the types must always match, and fix
the test by checking in both direction.
> value.Equals should check types in both directions

- internal/fixture/state.go
- merge/deduced_test.go
- merge/key_test.go
- merge/leaf_test.go
- merge/multiple_appliers_test.go
- merge/nested_test.go
- merge/obsolete_versions_test.go
- merge/preserve_unknown_test.go
- merge/real_test.go
- merge/set_test.go
- merge/union_test.go
This will make it possible to parse input objects with different
schemas, and test what happens if the schema changes, especially the
topology.
A few things need to happen in order to make this possible:
1. We need to be able to parse multiple different versions. A
ParseableType can only parse one type, so we need to pass in a parser
instead. The problem with the parser was that we needed a mapping to
know what was the name of the root type. Let's use the version name as
the root type. Now we can have multiple parseable type in the test.
2. Since most test actually use the same type with multiple different
version, we add a wrapper that let's you re-use the same type with
different versions.
3. DeducedType are usually all parsed the same for all versions, so
let's also create a helper for …
> Allow tests to specify objects in different versions

- fieldpath/fromvalue.go
- typed/remove.go
- value/list.go
- value/listreflect.go
- value/listunstructured.go
- value/map.go
- value/mapreflect.go
- value/mapunstructured.go
- value/structreflect.go
- value/value.go
- value/valuereflect.go
- value/valuereflect_test.go
- value/valueunstructured.go
- Avoid using `sync.Pool` for iteration loops where we can simply reuse an object directly.
- Introduce `List.Range` to make manage object reuse when looping over lists
- Use `List.Range` to optimize `ListEqual` and `ListCompare`
Benchmarks:
- `sync.Pool` change improves `BenchmarkConvertObjectToTyped` by ~20% for CPU
/sig api-machinery
/cc @apelisse @jennybuckley
> Optimize sync.Pool usage and value.Equals implementations

- value/fields.go
- value/listreflect.go
- value/mapreflect.go
- value/reflectcache.go
- value/structreflect.go
- value/valuereflect.go
- value/valuereflect_test.go
Extend the reflection cache introduced in https://github.com/kubernetes-sigs/structured-merge-diff/pull/136 to also track if a type implements `json.Marshal` and `json.Unmarshal`.
Changes:
- Avoid expensive `reflect.Implements` check on every object being converted by caching implements checks.
- Introduce a `UnstructuredConverter` interface that types like `Time` and `Quantity` can implement to directly convert to unstructured without going through JSON.
Net improvement is roughly 25% for CPU and 20% for allocations for `ObjectToTyped` and about 10% for CPU and allocations for `ToUnstructured`/ `FromUnstructured`.
This has been implemented such that `runtime.ToUnstructured` in `kubernetes/kubernetes` can be trivially modified to use this improvement simply by doing:
```
entry := …
```
> Optimize conversion to unstructured

- fieldpath/serialize.go
Compare the PathElement rather than calling twice in both direction. I don't think this has a "exponential" impact as it did in other places, but it's still the best thing to do.
I get a 2.5% time improvement on serialize tests. Nothing fancy.
@tedyu @jennybuckley
> Use Compare when serializing rather than Less

- fieldpath/fromvalue.go
- typed/helpers.go
- typed/merge.go
- typed/remove.go
- typed/tofieldset.go
- typed/validate.go
- value/list.go
- value/listreflect.go
- value/listunstructured.go
- value/map.go
- value/mapreflect.go
- value/mapunstructured.go
- value/reflectcache.go
- value/structreflect.go
- value/value.go
- value/valuereflect.go
- value/valuereflect_test.go
valueReflect uses 65% less CPU and 85% less allocations that valueUnstructured for ConvertToTyped, but for TypedValue.Compare it performs much worse:
**BEFORE:**
baseline: TypedValue.Compare using valueUnstructured
test variant: TypedValue.Compare using valueReflect
```
name               old time/op    new time/op    delta
Compare/Pod           100µs ± 3%     195µs ± 1%   +95.19%  (p=0.008 n=5+5)
Compare/Node          166µs ± 9%     280µs ± 0%   +68.38%  (p=0.008 n=5+5)
Compare/Endpoints    1.10ms ± 5%    0.02ms ± 2%   -98.39%  (p=0.008 n=5+5)
name               old alloc/op   new alloc/op   delta
Compare/Pod          11.3kB ± 0%    21.8kB ± 0%   +92.83%  (p=0.016 n=5+4)
Compare/Node         17.1kB ± 0%    40.7kB ± 0%  +137.37%  (p=0.008 n=5+5)
Compare/Endpoints    65.5kB ± 0%     2.6kB …
```
> Optimize TypedValue.Compare for value reflector

- fieldpath/fromvalue.go
- typed/helpers.go
- typed/merge.go
- typed/remove.go
- typed/tofieldset.go
- typed/typed.go
- typed/validate.go
- value/allocator.go
- value/list.go
- value/listreflect.go
- value/listunstructured.go
- value/map.go
- value/mapreflect.go
- value/mapunstructured.go
- value/reflectcache.go
- value/structreflect.go
- value/value.go
- value/valuereflect.go
- value/valuereflect_test.go
- value/valueunstructured.go
Remove use of `sync.Pool` entirely and add a `Allocator` interface that works like so:
```
allocator := value.NewFreelistAllocator()
val := m.GetUsing(allocator, "key")
...
// when done with the object:
allocator.Free(val)
```
The freelists themselves are pooled. The typical usage is to get a freelist from a pool when starting a traversal (e.g. validationWalker or mergeWalker) and then returned at the end of the traversal.
Callers that don't opt in to use the allocator by calling the "Using" functions get heap allocation by default.
The eliminates the contention observed by `sync.Pool` particularly when concurrency is high.
Test: Compare cpu=32 RunParallel benchmark that calls ObjectToTyped and then Compare, just like updater.Update does
Baseline: master + …
> Use freelists instead of sync.Pool for value object recycling

- value/reflectcache.go
- value/reflectcache_test.go
`k8s.io/apimachinery/pkg/runtime` tests failures from https://github.com/kubernetes/kubernetes/pull/87908 showed that `json.Marshaler` was not handled exactly right. We need to handle numbers in collections exactly as Kubernetes does.
> Convert numbers like Kubernetes does for json.Marshaler types

- fieldpath/managers.go
- fieldpath/managers_test.go
- internal/fixture/state.go
- merge/update.go
We need to know when the apply operation isn't changing the object, so
that we can update the timestamp of the operation. The simplest way to
do so it to return nil.
/assign @jennybuckley
> merge: Apply returns nil object if unchanged

- merge/conflict.go
- merge/conflict_test.go
Adds a method to merge.Conflicts to convert all conflicts to a fieldpath.Set.
We use this in https://github.com/kubernetes/kubernetes/pull/84134 when comparing merge.Conflicts to another Set (a Set of allowed conflicts).
> Add Conflicts.ToSet()

- merge/leaf_test.go
- merge/multiple_appliers_test.go
- merge/update.go
- typed/remove.go
- typed/typed.go
Implements the first part of the [WG Apply: Unsetting fields design](https://docs.google.com/document/d/11gUQY7Qvs1m53RTWzDzbOcDUZYMNRQCBQbTukpxmpSg/edit#heading=h.a715f9g8o54d):
Omitting a shared field from an applied configuration:
- Applier gives up ownership but the field remains unchanged.
Omit an exclusively owned field from an applied configuration:
- Optional field: field is removed or defaulted.
- Required field: the apply operation will fail with a validation error.
This makes fields consistent with how associative list/map items already behave.
Added a test converter that renames fields (e.g. conversion of v1 to v2 renames "field_v1"  to "field_v2") and used it to ensure that fields are unset when the unset is applied at a different version than the previous apply.
cc @apelisse …
> Remove fields that are omitted from applied configurations if there are no other owners

- merge/multiple_appliers_test.go
I wanted to ensure the behavior was what I expected so I wrote a test.
If there is already test coverage for this somewhere let me know, otherwise I think we should add it.
/sig api-machinery
/cc @apelisse
> Add test for multiple appliers with atomic maps

- internal/fixture/state.go
- merge/schema_change_test.go
- merge/update.go
- typed/reconcile_schema.go
- typed/reconcile_schema_test.go
- typed/typed.go
xref: [Design proposal](https://docs.google.com/document/d/1DUipHmrg0PTFsnS7QtMzTQWTC6num9GP0doVQmA3b8k/edit#)
Enables developers to safely add/remove these tags to Kubernetes types, by reconciling existing managed field data with the schema change:
- atomic tags: +listType=atomic, +structType=atomic, +mapType=atomic
- granular tags: +listType=map with +listMapKey, +listType=set, +mapType=granular
The corresponding x-kubernetes OpenAPI annotations for CRDs are also supported.
Need to do more careful benchmarking in k8s, but a simple benchmark in SMD suggests a 3.8% bump in CPU utilization and less than a 0.5% bump in allocations. The low allocation number is expected because the traversal is read-only unless there is an actual reconciliation change to apply afterward.
Before:
``` …
```
> Support granular<->atomic schema changes

- typed/reconcile_schema.go
Fixes a bug in https://github.com/kubernetes-sigs/structured-merge-diff/pull/170. Reporting an error is problematic for rollbacks and HA upgrades where a new field is introduced.
> Ignore fieldset paths not in schema when reconciling

- typed/reconcile_schema.go
- typed/reconcile_schema_test.go
If the managed fields for a complex type has no children fields (e.g. `emptyrDir: {}`), and the live object has not fields, skip reconciliation with schemas entirely.
Fixes the integration test failure in k8s: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/93901/pull-kubernetes-integration/1311377692632813568. How I reproduced:
```bash
kubectl apply -f hack/testdata/retainKeys/deployment/deployment-before.yaml
kubectl apply -f hack/testdata/retainKeys/deployment/deployment-after.yaml
kubectl get deployment test-deployment-retainkeys -oyaml | grep "emptyDir"
```
Before this fix, `emptyDir: {}` would match in the fieldset because reconciliation created a replacement fieldset for the emptyDir that has both a Member and an empty Children list (created as a side effect of calling …
> Fix noop granular case for atomic<->granular schema changes

- go.sum
- merge/default_keys_test.go
- schema/elements.go
- schema/equals.go
- schema/equals_test.go
- schema/schemaschema.go
- typed/helpers.go
- typed/merge.go
- typed/remove.go
- typed/tofieldset.go
- typed/validate.go
This is mostly a revival of #83 from @jennybuckley 
I've rebased it on master, which required a few changes. I've also decided to incorporate a couple of changes:
1. Allow validation of missing default-able associative keys rather than have a "unvalidated" parsing
2. Associate defaults to fields rather than strictly to associative lists (more general)
The tests that Jenny wrote are still passing, which I think is a good sign.
> Allow defaulted keys

- internal/fixture/state.go
- merge/default_keys_test.go
- typed/validate.go
This pull-request shows that even if the default is a float, this will still merge properly if someone applies with an integer for the field.
> Default keys float and int

- value/reflectcache.go
- value/valuereflect_test.go
This PR converts an embedded struct into its original type if it is
a pointer.
Fixes: https://github.com/kubernetes-sigs/structured-merge-diff/issues/172
> Fix panic on pointer to embedded struct

- value/reflectcache.go
- value/valuereflect_test.go
Cherry pick of #173 on release-3.0.
#173: Fix panic on pointer to embedded struct
> Cherry pick of #173: Fix panic on pointer to embedded struct

- fieldpath/set.go
- fieldpath/set_test.go
- merge/ignore_test.go
- merge/multiple_appliers_test.go
- merge/nested_test.go
- merge/update.go
- typed/tofieldset.go
Fixes #171 
This fixes a bug and slightly changes an existing behavior.
Struct that have a null value will now be owned, i.e.
```
struct:
```
will now be owned by whoever applies that (currently, these can't be owned, which means we may accidentally drop the empty struct).
Also, removing a struct will now remove all the items that are not owned by someone else in it (including things that are owned by an updater).
> Fix remove structures

- fieldpath/set.go
- fieldpath/set_test.go
- internal/fixture/state.go
- merge/extract_apply_test.go
- typed/remove.go
- typed/remove_test.go
- typed/typed.go
This exposes a new method on TypedValue called ExtractItems. Whereas
RemoveItems takes a fieldpath.Set adn returns the typed value with the
provided set items removed from it, ExtractItems returns ONLY those
items provided by the fieldpath.Set, effectively extracting them from
the original TypedValue.
> Expose ExtractItems as the opposite of RemoveItems

- merge/multiple_appliers_test.go
This should have been part of f09efb3313b4f4544756a0c89900c4a25787e054
> Fix benchmark broken by owning empty structs

- fieldpath/set.go
- fieldpath/set_test.go
- merge/leaf_test.go
- merge/multiple_appliers_test.go
- merge/nested_test.go
- merge/update.go
- typed/remove.go
- typed/tofieldset.go
- typed/typed.go
This is a not-clean cherry-pick of #166 and #184.
I also had to add the missing Schema function added in another PR but used in #184. Very minor though.
> Cherry pick 166 184

- typed/reconcile_schema.go
- typed/reconcile_schema_test.go
Mitigates https://github.com/kubernetes/kubernetes/issues/102749 by avoiding traversal of:
- CRD schemas that are deduced
- Branches of schemas where x-kubernetes-preserve-unknown-fields=true and there are no fields defined
For example, this will skip traversal for:
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
name: example.k8s.io
spec:
group: k8s.io
preserveUnknownFields: true
versions:
- name: v1
served: true
storage: true
```
and
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
...
schema:
openAPIV3Schema:
properties:
spec:
type: object
x-kubernetes-preserve-unknown-fields: true
status:
type: object
x-kubernetes-preserve-unknown-fields: true
```
But still do traversal for:
```yaml
apiVersion: apiextensions.k8s.io/v1 …
```
> Don't process schemaless fields with ReconcileFieldSetWithSchema

- schema/elements.go
- schema/elements_test.go
Now that schema.Schema has sync.Once attached, it makes no sense to encourage others to treat it as a value. This PR adds a `NewSchema` function as well as changes some usages of Schemas to use pointers rather than values.
> add CopyInto method to schema.Schema

- merge/multiple_appliers_test.go
- merge/update.go
Currently `addBackOwnedItems` adds back managed fields by API version in a random order (for range a map), consider the following scenario:
We have an object with two API versions: v1 and v2, and use a conversion webhook to convert between the two versions. When converting v2 to v1, the conversion webhook rely on a required field **foo** of v2.
Now there're several users use server-side apply to manage this object in different versions, when some user initiate a server-side apply to the object in v2, `addBackOwnedItems` would have to convert and add back fields to the pruned object in both v1 and v2. At this time, the order matters:
If `addBackOwnedItems` converts and adds back fields to v2 first then v1, everything will go smoothly, however, if the order is reversed, a `failed to convert …
> Fix potential conversion failure in addBackOwnedItems

- merge/real_test.go
Improve the way we invoke the parser in the Operations tests, so that we can later test against different schemas, and also have more than one test for the same type.
cc @alexzielenski
> Improve operations parsing

- internal/testdata/apiresourceimport-cr.yaml
- internal/testdata/apiresourceimport.yaml
- merge/real_test.go
- typed/merge.go
fixes an exponential recursion bug reproduced by the introduced benchmark 
occurs when attempting to merge `__untyped_deduced_` map with a nil value `lhs` and non-nil `rhs`. `deduceAtom` will just return the same input, so merge will create a new branch for recursion. Every nested level of fields ends up exponentially creating more merge branches. This PR adds logic so that the extra nil subtree is not traversed needlessly, and only the other operand's type is used for traversal.
> Fix exponential merge recursion

- internal/fixture/state.go
- internal/testdata/k8s-schema-100pct-fieldoverride.yaml
- internal/testdata/k8s-schema-10pct-fieldoverride.yaml
- merge/field_level_overrides_test.go
- merge/real_test.go
- schema/elements.go
- schema/elements_test.go
- schema/equals.go
- schema/equals_test.go
- schema/schemaschema.go
- typed/helpers.go
- typed/helpers_test.go
- typed/parser.go
- typed/reconcile_schema.go
- typed/typed.go
Part of our solution for https://github.com/kubernetes/kubernetes/pull/110495
Adds necessary functionality to support field-level annotations which may override the annotation of the referred type.
> add field-level element relationship which overrides referred type

- internal/testdata/k8s-deployment.yaml
- internal/testdata/node.yaml
**What type of PR is this?**
/kind cleanup
**What this PR does / why we need it**:
This PR replaces all `k8s.gcr.io` references with `registry.k8s.io`. See the linked issue for more details.
**Which issue(s) this PR fixes**:
xref https://github.com/kubernetes/k8s.io/issues/4738
**Release note**:
```
Replace all `k8s.gcr.io` references with `registry.k8s.io`
```
> Replace k8s.gcr.io with registry.k8s.io

- value/reflectcache.go
- value/reflectcache_test.go
Fixes #230 
This PR proposes to check an inlined struct field's kind before making a recursive call while building a cache entry for a struct [here](https://github.com/kubernetes-sigs/structured-merge-diff/blob/bbe0f82a74e23f330b2f85323da73e72f563c74a/value/reflectcache.go#L157), and adds some tests for `value.TypeReflectEntryOf`.
> Check inlined struct field's kind before recursively calling value.buildStructCacheEntry

- internal/fixture/state.go
Very minor nit. We have the diff when the managers don't match, but we don't print it which makes debugging harder than it has to be. Let's print it  to help.
> fixture: Show diff when managers don't match

- value/equals_test.go
- value/mapreflect.go
- value/mapunstructured.go
Currently, EqualsUsing recurses with Equals, which loses the allocator that you're using, defeating the whole point. Address that in all places I could find. I don't think that code-path is specifically used anywhere so this has no impact on benchmarks.
> Use EqualsUsing recursively

- typed/typed.go
Results are mostly positive, with some huge gains in some cases and minor negative gains in others.
```
name                                              old time/op    new time/op    delta
DeducedSimple-8                                     57.5µs ± 0%    59.4µs ± 0%   +3.19%  (p=0.008 n=5+5)
DeducedNested-8                                      123µs ± 0%     122µs ± 0%   -0.50%  (p=0.008 n=5+5)
DeducedNestedAcrossVersion-8                         167µs ± 0%     169µs ± 0%   +1.11%  (p=0.008 n=5+5)
LeafConflictAcrossVersion-8                         77.6µs ± 0%    81.4µs ± 0%   +4.80%  (p=0.008 n=5+5)
MultipleApplierRecursiveRealConversion-8            1.15ms ± 0%    1.16ms ± 0%   +0.54%  (p=0.008 n=5+5)
Operations/Pod/Create-8                             69.6µs ± 0%    70.1µs ± 0% …
```
> Use EqualsUsing in Typed.Compare()

- go.mod
- go.sum
- internal/fixture/state.go
- merge/obsolete_versions_test.go
- merge/real_test.go
- merge/set_test.go
- merge/update.go
Currently, we use the Compare function to compare objects, but this
doesn't look at the actual differences between objects, it collects the
fields from each object using smd logic and then compares that. This has
a couple of drawbacks:
1. Order is not preserved, which means anything that depends on order is
wrong!
2. When we decide to allow invalid duplicates, we won't be able to
compare such objects.
Use value.Equals to compare objects so that we have proper comparison,
and cmp.Diff in tests to highlight the differences.
As a consequence of 1, this has identified an interesting bug: we used
the comparison to see if two objects (before and after) were equal to
return nil as an output of `Apply`, but that logic doesn't check if the
order has changed, which caused some tests to fail (since …
> Do not use Compare for Equality checks

- merge/conflict.go
- merge/conflict_test.go
Since p is slice, its value is changed during the tree traversal(iterate). Hence use deep copy instead.
fixes https://github.com/kubernetes/kubernetes/issues/119141
> deep copy slice object during append

- typed/compare.go
- typed/typed.go
This is NOT an incompatible change. It doesn't change the behavior, doesn't change the API and should be safe to backport (and I'm planning on backporting this).
This is actually one of the first step to change the comparison function in order to solve the leniency problem.
/assign @jpbetz @alexzielenski 
/cc @thockin 
Performance improvements can be pretty noticeable for specific benchmarks (up to -50% in CPU).
```
name                                                    old time/op    new time/op    delta
pkg:sigs.k8s.io/structured-merge-diff/v4/merge goos:darwin goarch:amd64
DeducedSimple-8                                           65.6µs ±10%    59.0µs ± 0%   -9.98%  (p=0.016 n=5+4)
DeducedNested-8                                            135µs ± 6%     124µs ± 1%   -8.26%  (p=0.008 …
```
> Split merge and compare

- typed/parser.go
- typed/typed.go
- typed/validate.go
- typed/validate_test.go
If a set (or associative lists keys) has duplicated elements, then this will not fail the validation. Everything else is still the same.
> validation: Allow loose validation for sets

- typed/tofieldset.go
- typed/toset_test.go
Continuation of #247.
This uses the pattern that I've generally used to solve the problem, which is to not try to be too smart about duplicate entries, and just record the path element for the whole thing, rather than try to track all the fields within. It's not super relevant because no one should ever be able to apply duplicates, so they wouldn't really have conflicts with sub-fields anyway, we've decided that they should have a conflict with the idea of "duplicates" (de-duplicating is a conflict).
> tofieldset: Add tests to show it already allow duplicates

- fieldpath/pathelementmap.go
- fieldpath/pathelementmap_test.go
Minor change that will become important and was a little misleading to me. If you add something to the PathElementValueMap twice, the second value will be dropped (as opposed to the first).
> fieldpath: Allow map to be updated

- fieldpath/pathelementmap.go
- typed/compare.go
- typed/symdiff_test.go
Same strategy as #249, still trying to address #234. Algorithm goes as follow:
1. Duplicates are treated as separate from non-duplicates items
2. Adding a duplicate to an existing item means we will remove the existing (counted as removed) and added as a duplicate (added).
3. Removing does the opposite
4. If any of the duplicated value changes, key will be counted as "modified".
Rewording:
In compare, treat duplicate keys in associative lists/sets as a separate atomic list, marked by owning just the duplicated key.
/cc @jpbetz
> typed: Update compare algorithm to handle duplicates

- typed/merge.go
- typed/merge_test.go
The goal is to ignore duplicates if they are not included in the partial object, and to replace all of the occurences if they are in the partial object.
/assign @liggitt 
/cc @alexzielenski
> typed: Allow duplicates when we merge

- internal/fixture/state.go
- merge/duplicates_test.go
- merge/update.go
This not only affects merge but also `Compare` since they use the same algorithm/code.
Duplicates fields in a set/associative-list will now be treated as an atomic entity within that list, and will be entirely owned by the person who made them duplicates or who changed one of the duplicates.
That's the final fix for #234. This comes with extensive testing of all the scenarios I could think of. None of the existing behavior has changed.
/assign @liggitt @alexzielenski
> merge: Allow duplicate keys in lhs

- value/reflectcache.go
- value/reflectcache_test.go
Currently, when calling `ToUnstructured` on a `metav1.Time` that is a `nil` pointer, you get a panic:
```
panic: value method k8s.io/apimachinery/pkg/apis/meta/v1.Time.ToUnstructured called using nil *Time pointer
goroutine 1 [running]:
k8s.io/apimachinery/pkg/apis/meta/v1.(*Time).ToUnstructured(0x100000001?)
<autogenerated>:1 +0x48
sigs.k8s.io/structured-merge-diff/v4/value.TypeReflectCacheEntry.ToUnstructured({0x1, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, {0x0, 0x0, 0x0}}, ...)
external/io_k8s_sigs_structured_merge_diff_v4/value/reflectcache.go:192 +0x658
k8s.io/apimachinery/pkg/runtime.toUnstructured({0x108eaaf80?, 0x14001065390?, 0x1?}, {0x108686960?, 0x14003e181b0?, 0x98?})
external/io_k8s_apimachinery/pkg/runtime/converter.go:655 +0x6d4 …
```
> fix panic when calling ToUnstructured on nil metav1.Time

- value/reflectcache.go
- value/reflectcache_test.go
If a type's implementation of json.Marshaler returns bytes representing a valid JSON object or array followed by anything other than trailing whitespace, return an error rather than ignoring the trailing data. The documentation for the Marshaler interface indicates that implementations shouldn't do this, but it is safer to check (as json.Marshal does) than to rely on it.
> Error on conversion to unstructured for invalid json.Marshalers.

- fieldpath/fromvalue_test.go
- fieldpath/set_test.go
- go.mod
- go.sum
- merge/multiple_appliers_test.go
- typed/parser.go
- typed/parser_test.go
- value/equals_test.go
- value/value.go
We have our own fork of go-yaml https://github.com/kubernetes-sigs/yaml/pull/76 so we can simplify the dependency graph in kubernetes if we end the path in kubernetes-sigs/yaml
```
go mod why gopkg.in/yaml.v2
k8s.io/apiextensions-apiserver/examples/client-go/pkg/client/applyconfiguration/internal
sigs.k8s.io/structured-merge-diff/v4/typed
gopkg.in/yaml.v2
```
> use our own fork of go-yaml

- typed/remove_test.go
- typed/typed.go
This PR adds an option `AppendKeyFields` to the `ExtractItems` function. 
When doing extracting with a fieldpath set which doesn't include the key fields, with this option, the result would include the key field values. So that the extraction result would follow the schema without hitting key field missing errors.
Ref: #273
> feat: Adds ExtractItems option to include key fields

- value/scalar.go
Simple one-line change to avoid comparison to bool constant.
> chore: omit comparison to bool constant

- hack/apidiff.sh
For https://github.com/kubernetes-sigs/structured-merge-diff/issues/276
> feat: Adds a script to run apidiff

- .gitignore
- hack/apidiff.sh
fix error when execute apidiff.sh
1. 
```
./hack/apidiff.sh: line 58: GOBIN: unbound variable
```
2. 
```
./hack/apidiff.sh: line 98: apidiff: command not found
```
3. 
```
fatal: Not a valid object name origin/master
``` 
ref: https://github.com/kubernetes-sigs/structured-merge-diff/issues/276
> fix: update apidiff script to install tool and set up remote repository

- fieldpath/managers_test.go
- internal/cli/operation.go
- typed/validate.go
This is for addressing the change in go1.24
https://github.com/golang/go/issues/60529, which suppress the error on non-constant format and no args.
Fix: #281
> fix: update error formatting and test naming

- value/jsontagutil.go
- value/reflectcache.go
- value/reflectcache_test.go
xref https://github.com/kubernetes/kubernetes/pull/130989
> Add omitzero support

- go.mod
go is currently on 1.24 / 1.23, 1.19 is old enough to still support back to Kubernetes release-1.23 branch (10 releases behind the upcoming 1.33)
switching to a newer go version gives us improvements to module management
this is `go mod tidy` after bumping the `go` statement to 1.19
> bump go version to 1.19+

- fieldpath/element.go
- fieldpath/element_test.go
- fieldpath/set.go
- fieldpath/set_test.go
- go.mod
- value/fields.go
Sets of fields are useful throughout API machinery.  I'm currently working on extracting reachable fields from CEL expressions, and using fieldpath.Set makes a lot of sense.  But the code is a mess without these utilities.
Also bump to go 1.23 to pick up golang iterators.
> Add copy and iterator functions to fieldpath types

- fieldpath/fromvalue_test.go
- fieldpath/set_test.go
- go.mod
- go.sum
- merge/multiple_appliers_test.go
- typed/parser.go
- typed/parser_test.go
- value/equals_test.go
- value/value.go
Please see the following for context:
- https://github.com/kubernetes/kubernetes/issues/132056
- https://github.com/kubernetes/kubernetes/pull/132357
`"sigs.k8s.io/yaml/goyaml.v2"` is forked code and now there is a supported alternative in the larger community.
So essentially, we have to switch to using `go.yaml.in/yaml/v2`
> Drop usage of forked copies of goyaml.v2

- fieldpath/fieldpath_test.go
- fieldpath/managers_test.go
- fieldpath/serialize_test.go
- fieldpath/set_test.go
The tests were defined in the "fieldpath" package, which prevented using typed.NewParser (import cycle!). Defining them in "fieldpath_test" allows that. To avoid changing all references to the package's exported symbols, "fieldpath_test.go" defines aliases.
typed.NewParser is more strict and finds a typo in the test schema.
Also, constructing a set with `NewSet(MakePath(...))` was found to not yield the same structs as parsing a value with a schema, so now `parser.Type(typeName).FromYAML().ToFieldSet` is used instead.
> fieldpath: convert to blackbox testing
