- fieldpath/element.go
- fieldpath/set.go
- fieldpath/set_test.go
(also starts intersection and difference but now I have to go to a
meeting)
> Add union, equals

- fieldpath/set.go
- fieldpath/set_test.go
> Minor cleanup

- schema/elements.go
- typed/toset_test.go
- typed/typed.go
- typed/validate.go
Follow-up to #10 (merge that one first).
> add typed version of fieldset

- schema/elements.go
- typed/toset_test.go
- typed/validate.go
Builds on #11; the last three commits are new.
> Validation fixes

- fieldpath/set.go
- fieldpath/set_test.go
Reported in person by @apelisse.
> Fix Set.Difference: parent removal affects children

- schema/elements.go
- schema/schemaschema.go
- typed/helpers.go
- typed/merge_test.go
- typed/validate_test.go
Basically no bugs found and coverage is up a tad.
Possibly the most self-referential thing I've ever written?
In unrelated news, some error messages have been improved a touch.
> Add SchemaSchema, validate all schemas

- tests/examples/example_test.go
- tests/framework/impl.go
- tests/framework/parser.go
- tests/framework/state.go
- tests/framework/state_test.go
- typed/merge_test.go
- typed/parser.go
- typed/symdiff_test.go
- typed/toset_test.go
- typed/typed.go
- typed/validate_test.go
Create a class that helps parsing yaml using a given schema.
> Create YAML Parser with Schema validation

- merge/update.go
Create the signature for Updater, the object that will be used to update
the owners Fieldset and merge applied configurations.
> Create signature for Updater

- merge/conflict.go
- merge/conflict_test.go
- tests/framework/state.go
- typed/symdiff_test.go
- typed/typed.go
- Change conflict creation for convenience,
- Initialize some variables and fixes to the test framework,
- Diff test from nothing to something
- Add IsSame on comparison for convenience,
> Preparation for Updater code

- merge/owners.go
- merge/owners_test.go
- merge/update.go
Create the difference method to simplify comparison in tests.
> Move Owners logic to its file, add Difference

- merge/leaf_test.go
- merge/update.go
- merge/update_test.go
- smd/internal/operation.go
- smd/testdata/scalar-compare-output.txt
- typed/typed.go
Some tests for applying leaf fields, and updates from controllers.
Also some fixes that became obvious with tests :-)
> Add tests for leaf fields

- schema/doc.go
- schema/elements.go
Since the schema has drifted slightly from the document, try to document it (in godoc) very clearly.
> update godoc for schema

- fieldpath/doc.go
- typed/doc.go
- value/doc.go
I didn't add one for the merge package because it's a bit unfocused at the moment.
> Add missing documentation files

- merge/set_test.go
Some of the tests are currently broken (because the code is broken) and
are marked as skipped.
> Write tests for "sets"

- merge/leaf_test.go
- merge/set_test.go
- merge/update_test.go
Also require tabs instead of spaces for object yaml.
> Make tests more readable

- internal/fixture/state.go
- merge/leaf_test.go
- merge/set_test.go
- merge/update.go
And take the version as a parameter instead.
> Remove hard-coded version number

- schema/fromvalue.go
- schema/fromvalue_test.go
> generate schema from value function (for crds)

- schema/fromvalue_test.go
Addresses https://github.com/kubernetes-sigs/structured-merge-diff/pull/56/files#r248793479
> Fix test formatting from #56

- fieldpath/path.go
- internal/fixture/state.go
- merge/deduced_test.go
- merge/update.go
- typed/deduced.go
- typed/deduced_test.go
- typed/parser.go
- typed/typed.go
- typed/validate.go
- value/unstructured.go
Fixes everything for merging CRDs (schema-free types).
> Merge multiple types

- fieldpath/set.go
- merge/set_test.go
- merge/update.go
- typed/deduced.go
- typed/remove.go
- typed/typed.go
this fixes the broken test "apply_twice_remove"
Still room to refactor within remove.go because there was some code duplication
> Remove removed items from maps and lists on apply

- internal/fixture/state.go
- merge/update.go
> Don't try to convert to empty version

- merge/multiple_appliers_test.go
only have one right now, this is to track what we need to fix before multiple appliers works
> Add broken tests for multiple appliers

- merge/deduced_test.go
Add a couple more tests with more nested structures in deduced type to see that everything works as expected.
> Add nested test for deduced types

- internal/fixture/state.go
A few of things that are broken with conflicts:
- We're comparing strings with DeepEqual, which does care about the
order (and we're more considering it like a set, so it's sort-of
random).
- When we print the error, we don't distinguish between errors and
conflict errors, leading to a confusing message.
- When there is a difference we don't report specifically what it is, so
you have to match the sets yourself, which is unhelpful.
Address all of these by having a comparison function that helps us
detect what has changed, so that we can compare and report properly.
/assign @jennybuckley @kwiesmueller
> Fix bogus conflicts comparison and reporting

- merge/update.go
- typed/remove.go
This should fix the CI problems.
> Run gofmt -s

- merge/union_test.go
- schema/elements.go
- schema/schemaschema.go
- typed/typed.go
- typed/union.go
- typed/union_test.go
Implement support for multiple oneof's in the same structure.
/assign @jennybuckley 
/cc @lavalamp
> Oneof lists

- merge/update.go
We currently cache the versioned objects, which we use to then run the
comparison, but we don't need to cache the versioned object if we cache
the result of the comparison. This avoid a lot of extra comparisons.
> Cache Comparison result rather than versioned objects

- merge/deduced_test.go
- merge/leaf_test.go
- merge/multiple_appliers_test.go
This is testing the high-level part of SMD, we would probably need
lower-level benchmarks in this repo, but this at least gives us a
general idea of the direction.
/assign @lavalamp @jennybuckley
> Add benchmarks for merge package

- value/value.go
Doesn't seem to have a lot of impact performance wise, but certainly simpler to read.
> Use index rather than pointer in Map.Set/Get

- merge/update.go
Only a tiny effect on benchmarks, this is for correctness...
> disable one more union bit

- merge/real_test.go
- typed/parser_test.go
A couple of things:
1. It's probably more important to optimize update path rather than apply (since the former is much more frequent), but having benchmarks for Apply is still useful),
2. We also need to test performance for parsing since that's done a lot.
> Add even more benchmarks

- merge/update.go
Especially when doing update, we run Compare twice on the same objects, and it's a pretty expensive operation, so let's skip one. Most impacted benchmarks here:
```
benchmark                                              old ns/op     new ns/op     delta
BenchmarkOperations/Node/Update-12                     576277        268679        -53.38%
BenchmarkOperations/Pod/Update-12                      384166        191723        -50.09%
BenchmarkOperations/Endpoints/Update-12                55470         33445         -39.71%
benchmark                                              old allocs     new allocs     delta
BenchmarkOperations/Node/Update-12                     1155           601            -47.97%
BenchmarkOperations/Pod/Update-12                      843            445 …
```
> Remove duplicate run to Compare

- fieldpath/serialize_test.go
- typed/deduced_test.go
- typed/symdiff_test.go
- value/less_test.go
Use Fatalf rather than Errorf so that tests stop rather than panic later.
Also fix a small bug in a test.
> Minor tests improvements

- fieldpath/element.go
- fieldpath/element_test.go
- fieldpath/fromvalue.go
- fieldpath/fromvalue_test.go
- fieldpath/path.go
- fieldpath/serialize-pe.go
- fieldpath/set_test.go
- typed/helpers.go
- value/value.go
> Simplify PathElement Keys type

- typed/parser_test.go
We're only benchmarking "FromUnstructured" but there is no reason that "ToUnstructured" would have the exact same results.
> typed: Round-trip to/from unstructured in benchmark

- typed/helpers.go
- typed/symdiff_test.go
- typed/validate.go
- typed/validate_test.go
The validation error is quite ugly for users, I think back-porting this to the branch for 1.16 is reasonable.
/assign @kwiesmueller @jennybuckley
> Back-port Fix from Jenny for ugly errors

- schema/elements_test.go
- schema/equals.go
- schema/equals_test.go
- typed/merge.go
- typed/typed.go
This fixes data races caused by copied mutexes
/assign @apelisse
> make schema.Equals pointer receivers for Map and Schema

- merge/real_test.go
> Re-introduce benchmark test for Updates in different versions

- fieldpath/managers.go
- fieldpath/managers_test.go
- internal/fixture/state.go
- merge/update.go
- schema/elements_test.go
- schema/equals.go
- schema/equals_test.go
- typed/merge.go
- typed/typed.go
> Nil on noop apply

- merge/real_test.go
We don't have the best coverage for this.
> Add new ApplyTwice operation benchmark

- merge/multiple_appliers_test.go
- merge/update.go
I can't re-open #219, so just re-creating this.
> Add typename different from version test

- merge/nested_test.go
- schema/elements.go
- schema/elements_test.go
- schema/schemaschema.go
- typed/merge.go
- typed/typed.go
- typed/validate.go
A couple of minor fixes, including one to fix `go vet` which broke CI.
> Minor cleanups

- internal/testdata/schema.yaml
- schema/schemaschema.go
- typed/compare.go
- typed/helpers.go
- typed/merge.go
- typed/remove.go
- typed/tofieldset.go
- typed/validate.go
> Mild cleanups

- OWNERS
A few seasoned API Machinery contributors have graciously volunteered to help fill the reviewer ranks here.
Thanks @Jefftree @yliaog @cici37 
/sig api-machinery
/assign @apelisse
> Add volunteer reviewers

- go.mod
- go.sum
- schema/equals_test.go
> Switch from gofuzz to randfill
